//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tauron.Application.ImageOrganizer.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BuissinesLayerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuissinesLayerResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tauron.Application.ImageOrganizer.BL.Resources.BuissinesLayerResources", typeof(BuissinesLayerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading Files {0}/{1} ähnelt.
        /// </summary>
        internal static string FileImporterRule_ImportFiles {
            get {
                return ResourceManager.GetString("FileImporterRule_ImportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save To Database ähnelt.
        /// </summary>
        internal static string FileImporterRule_SaveToDatabase {
            get {
                return ResourceManager.GetString("FileImporterRule_SaveToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Files: {0}/{1} ähnelt.
        /// </summary>
        internal static string FileImporterRule_SaveZip {
            get {
                return ResourceManager.GetString("FileImporterRule_SaveZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorting Image Entrys ähnelt.
        /// </summary>
        internal static string FileImporterRule_SortingEntrys {
            get {
                return ResourceManager.GetString("FileImporterRule_SortingEntrys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Staging Entrys ähnelt.
        /// </summary>
        internal static string FileImporterRule_StagingEntrys {
            get {
                return ResourceManager.GetString("FileImporterRule_StagingEntrys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prepare ähnelt.
        /// </summary>
        internal static string FileImporterRule_Starting {
            get {
                return ResourceManager.GetString("FileImporterRule_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Readable (To manay Requests) ähnelt.
        /// </summary>
        internal static string Sankaku_NotReadable {
            get {
                return ResourceManager.GetString("Sankaku_NotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unkowen Error ähnelt.
        /// </summary>
        internal static string SankakuFetcher_CommonError {
            get {
                return ResourceManager.GetString("SankakuFetcher_CommonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sankaku Provider ähnelt.
        /// </summary>
        internal static string SankakuFetcher_Name {
            get {
                return ResourceManager.GetString("SankakuFetcher_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Download Data ähnelt.
        /// </summary>
        internal static string SankakuProvider_DownlodInvalid {
            get {
                return ResourceManager.GetString("SankakuProvider_DownlodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Sankaku Post ähnelt.
        /// </summary>
        internal static string SankakuProvider_InvalidFile {
            get {
                return ResourceManager.GetString("SankakuProvider_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dictionary Not Exis  ähnelt.
        /// </summary>
        internal static string SwitchContainnerRule_DicNotExis {
            get {
                return ResourceManager.GetString("SwitchContainnerRule_DicNotExis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To Low Space Ready ähnelt.
        /// </summary>
        internal static string SwitchContainnerRule_LowSpace {
            get {
                return ResourceManager.GetString("SwitchContainnerRule_LowSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unkowen Confugration ähnelt.
        /// </summary>
        internal static string SwitchContainnerRule_UnknowenConfig {
            get {
                return ResourceManager.GetString("SwitchContainnerRule_UnknowenConfig", resourceCulture);
            }
        }
    }
}
