//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tauron.Application.ImageOrginazer.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tauron.Application.ImageOrginazer.ViewModels.Resources.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Common_Label_Back {
            get {
                return ResourceManager.GetString("Common_Label_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recuvery ähnelt.
        /// </summary>
        public static string ContainerManager_ButtionLabel_Recuvery {
            get {
                return ResourceManager.GetString("ContainerManager_ButtionLabel_Recuvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string ContainerManager_ButtonLabel_Apply {
            get {
                return ResourceManager.GetString("ContainerManager_ButtonLabel_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Both ähnelt.
        /// </summary>
        public static string ContainerManager_ContainerType_Compose {
            get {
                return ResourceManager.GetString("ContainerManager_ContainerType_Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multi Files ähnelt.
        /// </summary>
        public static string ContainerManager_ContainerType_Multi {
            get {
                return ResourceManager.GetString("ContainerManager_ContainerType_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single Container ähnelt.
        /// </summary>
        public static string ContainerManager_ContainerType_Single {
            get {
                return ResourceManager.GetString("ContainerManager_ContainerType_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Container Type: ähnelt.
        /// </summary>
        public static string ContainerManager_ContainerTypeCombobox_Header {
            get {
                return ResourceManager.GetString("ContainerManager_ContainerTypeCombobox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Multi File Path: ähnelt.
        /// </summary>
        public static string ContainerManager_CustomPath_Label {
            get {
                return ResourceManager.GetString("ContainerManager_CustomPath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse ähnelt.
        /// </summary>
        public static string ContainerManager_CustomPathButton_Label {
            get {
                return ResourceManager.GetString("ContainerManager_CustomPathButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Path for Files. ähnelt.
        /// </summary>
        public static string ContainerManager_CustomPathSearch_Description {
            get {
                return ResourceManager.GetString("ContainerManager_CustomPathSearch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Container Syncronzied ähnelt.
        /// </summary>
        public static string ContainerManager_ErrorType_Add {
            get {
                return ResourceManager.GetString("ContainerManager_ErrorType_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deta Deleted ähnelt.
        /// </summary>
        public static string ContainerManager_ErrorType_Deleted {
            get {
                return ResourceManager.GetString("ContainerManager_ErrorType_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Missing ähnelt.
        /// </summary>
        public static string ContainerManager_ErrorType_Missing {
            get {
                return ResourceManager.GetString("ContainerManager_ErrorType_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defragmentation is Needed ähnelt.
        /// </summary>
        public static string ContainerManager_NeedSync_Message {
            get {
                return ResourceManager.GetString("ContainerManager_NeedSync_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder for Recuvery ähnelt.
        /// </summary>
        public static string ContainerManager_OpenFolder_Recuvery {
            get {
                return ResourceManager.GetString("ContainerManager_OpenFolder_Recuvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Container Manager ähnelt.
        /// </summary>
        public static string ContainerManager_ProgrammTitle {
            get {
                return ResourceManager.GetString("ContainerManager_ProgrammTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current: {0} ähnelt.
        /// </summary>
        public static string ContainerManager_RecuveryProgress_Run {
            get {
                return ResourceManager.GetString("ContainerManager_RecuveryProgress_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defragmentaion ähnelt.
        /// </summary>
        public static string ContainerManager_SyncButton_Label {
            get {
                return ResourceManager.GetString("ContainerManager_SyncButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prepare ähnelt.
        /// </summary>
        public static string ContianerManager_RecuveryProgress_Start {
            get {
                return ResourceManager.GetString("ContianerManager_RecuveryProgress_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Open ähnelt.
        /// </summary>
        public static string Dialog_Title_Open {
            get {
                return ResourceManager.GetString("Dialog_Title_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Manager ähnelt.
        /// </summary>
        public static string DonwloadManager_ProgrammTitle {
            get {
                return ResourceManager.GetString("DonwloadManager_ProgrammTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        public static string DownloadManager_ButtonLabel_Pause {
            get {
                return ResourceManager.GetString("DownloadManager_ButtonLabel_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resume ähnelt.
        /// </summary>
        public static string DownloadManager_ButtonLabel_Resume {
            get {
                return ResourceManager.GetString("DownloadManager_ButtonLabel_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Image Download ähnelt.
        /// </summary>
        public static string DownloadManager_ButtonLabel_StartImageDowload {
            get {
                return ResourceManager.GetString("DownloadManager_ButtonLabel_StartImageDowload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target Date ähnelt.
        /// </summary>
        public static string DownloadManager_DataGrid_DownloadDate {
            get {
                return ResourceManager.GetString("DownloadManager_DataGrid_DownloadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Stade ähnelt.
        /// </summary>
        public static string DownloadManager_DataGrid_DownloadStade {
            get {
                return ResourceManager.GetString("DownloadManager_DataGrid_DownloadStade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Type ähnelt.
        /// </summary>
        public static string DownloadManager_DataGrid_DownloadType {
            get {
                return ResourceManager.GetString("DownloadManager_DataGrid_DownloadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed Reason ähnelt.
        /// </summary>
        public static string DownloadManager_DataGrid_FailedReason {
            get {
                return ResourceManager.GetString("DownloadManager_DataGrid_FailedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag a colum header here to group by that column ähnelt.
        /// </summary>
        public static string DownloadManager_DataGrid_GroupDropArea {
            get {
                return ResourceManager.GetString("DownloadManager_DataGrid_GroupDropArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metadata ähnelt.
        /// </summary>
        public static string DownloadManager_DataGrid_Metadata {
            get {
                return ResourceManager.GetString("DownloadManager_DataGrid_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image ähnelt.
        /// </summary>
        public static string DownloadManager_DataGrid_NameLabel {
            get {
                return ResourceManager.GetString("DownloadManager_DataGrid_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        public static string FileImporter_Button_SelectFiles {
            get {
                return ResourceManager.GetString("FileImporter_Button_SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string FileImporter_Button_Start {
            get {
                return ResourceManager.GetString("FileImporter_Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string FileImporter_DataGrid_Date {
            get {
                return ResourceManager.GetString("FileImporter_DataGrid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string FileImporter_DataGrid_Name {
            get {
                return ResourceManager.GetString("FileImporter_DataGrid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full Path ähnelt.
        /// </summary>
        public static string FileImporter_DataGrid_Path {
            get {
                return ResourceManager.GetString("FileImporter_DataGrid_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        /// </summary>
        public static string FileImporter_DataGrid_Size {
            get {
                return ResourceManager.GetString("FileImporter_DataGrid_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Count: ähnelt.
        /// </summary>
        public static string FileImporter_Label_FileCount {
            get {
                return ResourceManager.GetString("FileImporter_Label_FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provider: ähnelt.
        /// </summary>
        public static string FileImporter_Label_Provider {
            get {
                return ResourceManager.GetString("FileImporter_Label_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Folder ähnelt.
        /// </summary>
        public static string FileImporter_OpenFolder_Title {
            get {
                return ResourceManager.GetString("FileImporter_OpenFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Importer ähnelt.
        /// </summary>
        public static string FileImporter_Programm_Title {
            get {
                return ResourceManager.GetString("FileImporter_Programm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder: ähnelt.
        /// </summary>
        public static string FileImprter_Label_SelectFiles {
            get {
                return ResourceManager.GetString("FileImprter_Label_SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag Type Editor ähnelt.
        /// </summary>
        public static string ImageEdito_TabHeadert_TagTypeEditor {
            get {
                return ResourceManager.GetString("ImageEdito_TabHeadert_TagTypeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count: {MaxCount} ähnelt.
        /// </summary>
        public static string ImageEditor_CommonCount_Format {
            get {
                return ResourceManager.GetString("ImageEditor_CommonCount_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Added ähnelt.
        /// </summary>
        public static string ImageEditor_ImageRowheader_Added {
            get {
                return ResourceManager.GetString("ImageEditor_ImageRowheader_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author ähnelt.
        /// </summary>
        public static string ImageEditor_ImageRowHeader_Author {
            get {
                return ResourceManager.GetString("ImageEditor_ImageRowHeader_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorite ähnelt.
        /// </summary>
        public static string ImageEditor_ImageRowHeader_Favorite {
            get {
                return ResourceManager.GetString("ImageEditor_ImageRowHeader_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Id ähnelt.
        /// </summary>
        public static string ImageEditor_ImageRowHeader_Id {
            get {
                return ResourceManager.GetString("ImageEditor_ImageRowHeader_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ImageEditor_ImageRowHeader_Name {
            get {
                return ResourceManager.GetString("ImageEditor_ImageRowHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provider ähnelt.
        /// </summary>
        public static string ImageEditor_ImageRowHeader_ProviderName {
            get {
                return ResourceManager.GetString("ImageEditor_ImageRowHeader_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tags Count ähnelt.
        /// </summary>
        public static string ImageEditor_ImageRowHeader_TagsCount {
            get {
                return ResourceManager.GetString("ImageEditor_ImageRowHeader_TagsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Image ähnelt.
        /// </summary>
        public static string ImageEditor_ImageRowHeader_UpdateTags {
            get {
                return ResourceManager.GetString("ImageEditor_ImageRowHeader_UpdateTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate Image ähnelt.
        /// </summary>
        public static string ImageEditor_ImageValidate_Name_Duplicate {
            get {
                return ResourceManager.GetString("ImageEditor_ImageValidate_Name_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Name ähnelt.
        /// </summary>
        public static string ImageEditor_ImageValidate_Name_Null {
            get {
                return ResourceManager.GetString("ImageEditor_ImageValidate_Name_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imager Editor ähnelt.
        /// </summary>
        public static string ImageEditor_ProgrammTitle {
            get {
                return ResourceManager.GetString("ImageEditor_ProgrammTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queued ähnelt.
        /// </summary>
        public static string ImageEditor_SpecialUpdate_Compled {
            get {
                return ResourceManager.GetString("ImageEditor_SpecialUpdate_Compled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed ähnelt.
        /// </summary>
        public static string ImageEditor_SpecialUpdate_Failed {
            get {
                return ResourceManager.GetString("ImageEditor_SpecialUpdate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ImageEditor ähnelt.
        /// </summary>
        public static string ImageEditor_TabHeader_ImageEditor {
            get {
                return ResourceManager.GetString("ImageEditor_TabHeader_ImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag Editor ähnelt.
        /// </summary>
        public static string ImageEditor_TabHeader_TagsEditor {
            get {
                return ResourceManager.GetString("ImageEditor_TabHeader_TagsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Tags ähnelt.
        /// </summary>
        public static string ImageEditor_TagGridStatus_All {
            get {
                return ResourceManager.GetString("ImageEditor_TagGridStatus_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string ImageEditor_TagRowHeader_Description {
            get {
                return ResourceManager.GetString("ImageEditor_TagRowHeader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ImageEditor_TagRowHeader_Name {
            get {
                return ResourceManager.GetString("ImageEditor_TagRowHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string ImageEditor_TagRowHeader_Type {
            get {
                return ResourceManager.GetString("ImageEditor_TagRowHeader_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving Tags ähnelt.
        /// </summary>
        public static string ImageEditor_TagsButton_Save {
            get {
                return ResourceManager.GetString("ImageEditor_TagsButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color ähnelt.
        /// </summary>
        public static string ImageEditor_TagTypeHeader_Color {
            get {
                return ResourceManager.GetString("ImageEditor_TagTypeHeader_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ImageEditor_TagTypeHeader_Name {
            get {
                return ResourceManager.GetString("ImageEditor_TagTypeHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transparent not Allowed ähnelt.
        /// </summary>
        public static string ImageEditor_TagTypeValidate_Color {
            get {
                return ResourceManager.GetString("ImageEditor_TagTypeValidate_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate Name ähnelt.
        /// </summary>
        public static string ImageEditor_TagTypeValidate_Name {
            get {
                return ResourceManager.GetString("ImageEditor_TagTypeValidate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate Tag ähnelt.
        /// </summary>
        public static string ImageEditor_TagValidate_Name {
            get {
                return ResourceManager.GetString("ImageEditor_TagValidate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty ähnelt.
        /// </summary>
        public static string ImageViewer__Label_Empty {
            get {
                return ResourceManager.GetString("ImageViewer _Label_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string ImageViewer_Button_Reset {
            get {
                return ResourceManager.GetString("ImageViewer_Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Date Not Found ähnelt.
        /// </summary>
        public static string ImageViewer_Error_DataInvalid {
            get {
                return ResourceManager.GetString("ImageViewer_Error_DataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Images Found ähnelt.
        /// </summary>
        public static string ImageViewer_Error_NoData {
            get {
                return ResourceManager.GetString("ImageViewer_Error_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock ähnelt.
        /// </summary>
        public static string ImageViewer_LockScreeen_Button {
            get {
                return ResourceManager.GetString("ImageViewer_LockScreeen_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lock Screen ähnelt.
        /// </summary>
        public static string ImageViewer_LockScreeen_Label {
            get {
                return ResourceManager.GetString("ImageViewer_LockScreeen_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No File Selected ähnelt.
        /// </summary>
        public static string ImageViewerModel_InvalidDatabase {
            get {
                return ResourceManager.GetString("ImageViewerModel_InvalidDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordered ähnelt.
        /// </summary>
        public static string ImageViewerModel_PagerName_Ordered {
            get {
                return ResourceManager.GetString("ImageViewerModel_PagerName_Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Random ähnelt.
        /// </summary>
        public static string ImageViewerModel_PagerName_Random {
            get {
                return ResourceManager.GetString("ImageViewerModel_PagerName_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Container Manager ähnelt.
        /// </summary>
        public static string MainMenu_ContainerManager {
            get {
                return ResourceManager.GetString("MainMenu_ContainerManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Image ähnelt.
        /// </summary>
        public static string MainMenu_DeleteImage {
            get {
                return ResourceManager.GetString("MainMenu_DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Donwload Manager ähnelt.
        /// </summary>
        public static string MainMenu_DonwnloadManager {
            get {
                return ResourceManager.GetString("MainMenu_DonwnloadManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Files ähnelt.
        /// </summary>
        public static string MainMenu_FileImport {
            get {
                return ResourceManager.GetString("MainMenu_FileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string MainMenu_FileItem {
            get {
                return ResourceManager.GetString("MainMenu_FileItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close File ähnelt.
        /// </summary>
        public static string MainMenu_FileItem_Close {
            get {
                return ResourceManager.GetString("MainMenu_FileItem_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Open ähnelt.
        /// </summary>
        public static string MainMenu_FileItem_Open {
            get {
                return ResourceManager.GetString("MainMenu_FileItem_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image ähnelt.
        /// </summary>
        public static string MainMenu_Image {
            get {
                return ResourceManager.GetString("MainMenu_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Editor ähnelt.
        /// </summary>
        public static string MainMenu_ImageEditor {
            get {
                return ResourceManager.GetString("MainMenu_ImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images ähnelt.
        /// </summary>
        public static string MainMenu_ImageView {
            get {
                return ResourceManager.GetString("MainMenu_ImageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile Manager ähnelt.
        /// </summary>
        public static string MainMenu_ProfileManager {
            get {
                return ResourceManager.GetString("MainMenu_ProfileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiles ähnelt.
        /// </summary>
        public static string MainMenu_Profiles {
            get {
                return ResourceManager.GetString("MainMenu_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Re Download ähnelt.
        /// </summary>
        public static string MainMenu_RedownloadImage {
            get {
                return ResourceManager.GetString("MainMenu_RedownloadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace Image ähnelt.
        /// </summary>
        public static string MainMenu_ReplaceImage {
            get {
                return ResourceManager.GetString("MainMenu_ReplaceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        public static string MainMenu_View {
            get {
                return ResourceManager.GetString("MainMenu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CreateResult Profile ähnelt.
        /// </summary>
        public static string MainWindow_Button_CreateProfile {
            get {
                return ResourceManager.GetString("MainWindow_Button_CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        public static string MainWindow_Button_Pause {
            get {
                return ResourceManager.GetString("MainWindow_Button_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        public static string MainWindow_Button_Stop {
            get {
                return ResourceManager.GetString("MainWindow_Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorites ähnelt.
        /// </summary>
        public static string MainWindow_FavoriteFilter_Label {
            get {
                return ResourceManager.GetString("MainWindow_FavoriteFilter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Name was Invalid. ähnelt.
        /// </summary>
        public static string MainWindow_ProfileCreationError_InvalidName {
            get {
                return ResourceManager.GetString("MainWindow_ProfileCreationError_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Page: {0} (Index: {1}) ähnelt.
        /// </summary>
        public static string MainWindow_StatusBar_ImagePostion {
            get {
                return ResourceManager.GetString("MainWindow_StatusBar_ImagePostion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Database ähnelt.
        /// </summary>
        public static string MainWindow_StatusBar_NoDatabase {
            get {
                return ResourceManager.GetString("MainWindow_StatusBar_NoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Image ähnelt.
        /// </summary>
        public static string MainWindow_StatusBar_NoImage {
            get {
                return ResourceManager.GetString("MainWindow_StatusBar_NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Downloads ähnelt.
        /// </summary>
        public static string MainWindow_StatusbarLabel_Downloads {
            get {
                return ResourceManager.GetString("MainWindow_StatusbarLabel_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile: {0} ähnelt.
        /// </summary>
        public static string MainWindow_StatusBas_ActiveProfile {
            get {
                return ResourceManager.GetString("MainWindow_StatusBas_ActiveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search: ähnelt.
        /// </summary>
        public static string MainWindow_TextBlock_SearchLabel {
            get {
                return ResourceManager.GetString("MainWindow_TextBlock_SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace Image Failed ähnelt.
        /// </summary>
        public static string MainWWindowViewModel_Replace_Failed {
            get {
                return ResourceManager.GetString("MainWWindowViewModel_Replace_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview Image ähnelt.
        /// </summary>
        public static string PreviewWindow_Title {
            get {
                return ResourceManager.GetString("PreviewWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string ProfileManager_Button_Create {
            get {
                return ResourceManager.GetString("ProfileManager_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string ProfileManager_ButtonLabel_EditSql {
            get {
                return ResourceManager.GetString("ProfileManager_ButtonLabel_EditSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
        /// </summary>
        public static string ProfileManager_ButtonLabel_Preview {
            get {
                return ResourceManager.GetString("ProfileManager_ButtonLabel_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Query ähnelt.
        /// </summary>
        public static string ProfileManager_ButtonLabel_StartQuery {
            get {
                return ResourceManager.GetString("ProfileManager_ButtonLabel_StartQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch ähnelt.
        /// </summary>
        public static string ProfileManager_ButtonLabel_Switch {
            get {
                return ResourceManager.GetString("ProfileManager_ButtonLabel_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Profile already exis. ähnelt.
        /// </summary>
        public static string ProfileManager_Create_Duplicate {
            get {
                return ResourceManager.GetString("ProfileManager_Create_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ProfileManager_CreateLabel_Caption {
            get {
                return ResourceManager.GetString("ProfileManager_CreateLabel_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter Name of new Profile. ähnelt.
        /// </summary>
        public static string ProfileManager_CreateLable_Instruction {
            get {
                return ResourceManager.GetString("ProfileManager_CreateLable_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT *
        ///FROM Images
        ///ORDER BY
        /// Name ASC; ähnelt.
        /// </summary>
        public static string ProfileManager_DefaultQuery {
            get {
                return ResourceManager.GetString("ProfileManager_DefaultQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Override Profile ähnelt.
        /// </summary>
        public static string ProfileManager_OverrideProfile_Caption {
            get {
                return ResourceManager.GetString("ProfileManager_OverrideProfile_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to override the profile ähnelt.
        /// </summary>
        public static string ProfileManager_OverrideProfile_Text {
            get {
                return ResourceManager.GetString("ProfileManager_OverrideProfile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Image Page ähnelt.
        /// </summary>
        public static string ProfileManager_ProfileDataUi_CurrentImages {
            get {
                return ResourceManager.GetString("ProfileManager_ProfileDataUi_CurrentImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Image Index ähnelt.
        /// </summary>
        public static string ProfileManager_ProfileDataUi_CurrentPosition {
            get {
                return ResourceManager.GetString("ProfileManager_ProfileDataUi_CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorite Filter ähnelt.
        /// </summary>
        public static string ProfileManager_ProfileDataUi_Favorite {
            get {
                return ResourceManager.GetString("ProfileManager_ProfileDataUi_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter Text ähnelt.
        /// </summary>
        public static string ProfileManager_ProfileDataUi_FilterString {
            get {
                return ResourceManager.GetString("ProfileManager_ProfileDataUi_FilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ProfileManager_ProfileDataUi_Name {
            get {
                return ResourceManager.GetString("ProfileManager_ProfileDataUi_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Image Page ähnelt.
        /// </summary>
        public static string ProfileManager_ProfileDataUi_NextImages {
            get {
                return ResourceManager.GetString("ProfileManager_ProfileDataUi_NextImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page Mode ähnelt.
        /// </summary>
        public static string ProfileManager_ProfileDataUi_PageType {
            get {
                return ResourceManager.GetString("ProfileManager_ProfileDataUi_PageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile Manager ähnelt.
        /// </summary>
        public static string ProfileManager_ProgrammTitle {
            get {
                return ResourceManager.GetString("ProfileManager_ProgrammTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sankaku ähnelt.
        /// </summary>
        public static string Provider_Sankaku {
            get {
                return ResourceManager.GetString("Provider_Sankaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string ProviderNon {
            get {
                return ResourceManager.GetString("ProviderNon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string QueryEditorWindow_ButtonLabel_OK {
            get {
                return ResourceManager.GetString("QueryEditorWindow_ButtonLabel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query Editor ähnelt.
        /// </summary>
        public static string QueryEditorWindow_Title {
            get {
                return ResourceManager.GetString("QueryEditorWindow_Title", resourceCulture);
            }
        }
    }
}
